import type { SafetyPlaybook, SafetyState } from "@/lib/safety-core/contracts";

export const safetyPlaybooks: Record<SafetyState, SafetyPlaybook> = {
  normal_support: {
    state: "normal_support",
    severity: "low",
    nextRecommendedAction: "continue_chat",
    responseType: "normal_chat",
    allowNormalChat: true,
    allowClarityMap: true,
    showSafetyCard: false,
    showResources: false,
    resourceTopics: [],
    mode: "normal",
  },
  elevated_distress: {
    state: "elevated_distress",
    severity: "medium",
    nextRecommendedAction: "continue_with_supportive_nudge",
    responseType: "supportive_nudge",
    allowNormalChat: true,
    allowClarityMap: true,
    showSafetyCard: true,
    showResources: true,
    resourceTopics: ["support", "professional_support"],
    mode: "support",
  },
  passive_suicidal_ideation: {
    state: "passive_suicidal_ideation",
    severity: "high",
    nextRecommendedAction: "show_resources",
    responseType: "safety",
    allowNormalChat: false,
    allowClarityMap: false,
    showSafetyCard: true,
    showResources: true,
    resourceTopics: ["self_harm", "crisis", "support"],
    mode: "support",
  },
  active_suicidal_ideation: {
    state: "active_suicidal_ideation",
    severity: "high",
    nextRecommendedAction: "show_resources",
    responseType: "safety",
    allowNormalChat: false,
    allowClarityMap: false,
    showSafetyCard: true,
    showResources: true,
    resourceTopics: ["self_harm", "crisis", "support"],
    mode: "support",
  },
  imminent_risk: {
    state: "imminent_risk",
    severity: "imminent",
    nextRecommendedAction: "urgent_support",
    responseType: "urgent_safety",
    allowNormalChat: false,
    allowClarityMap: false,
    showSafetyCard: true,
    showResources: true,
    resourceTopics: ["self_harm", "crisis", "emergency"],
    mode: "crisis",
  },
  self_harm_method_request: {
    state: "self_harm_method_request",
    severity: "imminent",
    nextRecommendedAction: "urgent_support",
    responseType: "urgent_safety",
    allowNormalChat: false,
    allowClarityMap: false,
    showSafetyCard: true,
    showResources: true,
    resourceTopics: ["self_harm", "crisis", "emergency"],
    mode: "crisis",
  },
  medical_emergency: {
    state: "medical_emergency",
    severity: "high",
    nextRecommendedAction: "urgent_support",
    responseType: "urgent_safety",
    allowNormalChat: false,
    allowClarityMap: false,
    showSafetyCard: true,
    showResources: true,
    resourceTopics: ["medical_emergency", "emergency"],
    mode: "crisis",
  },
  harm_to_others: {
    state: "harm_to_others",
    severity: "imminent",
    nextRecommendedAction: "urgent_support",
    responseType: "urgent_safety",
    allowNormalChat: false,
    allowClarityMap: false,
    showSafetyCard: true,
    showResources: true,
    resourceTopics: ["harm_to_others", "emergency"],
    mode: "crisis",
  },
  abuse_or_coercion: {
    state: "abuse_or_coercion",
    severity: "high",
    nextRecommendedAction: "show_resources",
    responseType: "safety",
    allowNormalChat: false,
    allowClarityMap: false,
    showSafetyCard: true,
    showResources: true,
    resourceTopics: ["abuse", "safety", "support"],
    mode: "support",
  },
  policy_boundary: {
    state: "policy_boundary",
    severity: "medium",
    nextRecommendedAction: "continue_with_supportive_nudge",
    responseType: "boundary",
    allowNormalChat: false,
    allowClarityMap: false,
    showSafetyCard: false,
    showResources: false,
    resourceTopics: [],
    mode: "support",
  },
};

export function getSafetyPlaybook(state: SafetyState) {
  return safetyPlaybooks[state];
}
